acme/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from .import views

handler404 = 'acme.views.handler404'
handler500 = 'acme.views.handler500'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),   
    url(r'^posts/(?P<id>[0-9]+)$', views.show, name='show'),
]

blog/models.py
from django.db import models

# Create your models here.
class TimestampModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Post(TimestampModel):
    title = models.CharField(max_length=255)
    body = models.TextField()

    def __str__(self):
        return self.title

acme/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'pages/home.html')

def about(request):
    return render(request, 'pages/about.html')

def contact(request):
    return render(request, 'pages/contact.html')

def handler404(request, exception=None):
    return render(request, 'errors/404.html', {'error':exception}, status=404)

def handler500(request, exception=None):
    return render(request, 'errors/500.html', {}, status=500)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
# Create your views here.

#from .mocks import Post
from .models import Post

def index(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html', {'posts':posts})

def show(request, id):
    post = get_object_or_404(Post, pk=id)
    #try:
    #    post = Post.objects.get(pk=id)
    #except Post.DoesNotExist:
    #    raise  Http404('Sorry, post #{} not found'.format(id))

    return render(request, 'blog/show.html', {'post':post})

blog/templates/blog/base.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'blog/css/styles.css' %}">
{% endblock stylesheets %}

{% block content %}
    <h1>Blog</h1>

    {% block body %}{% endblock body %}
{% endblock content %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}


{% block title %}Blog{% endblock title %}


{% block body %}

    <h1>{{posts|length}} posts</h1>

    {% for post in posts %}
        <article>
            <h2 class="title">
                <a href="{% url 'blog:show' post.id %}">#{{post.id}} - {{post.title}}</a>
            </h2>
            
            <p class="time">
                <time datetime="{{post.created_at|date:'Y-m-d'}}">
                    Posted {{post.created_at|timesince}} ago
                </time>
            </p>
            <p class="content">{{post.body|truncatewords:3}}</p>
        </article>


        {% empty %}
            <p>Sorry, no post availble</p>
    {% endfor %}

{% endblock body %}

blog/templates/blog/show.html
{% extends 'blog/base.html' %}

{% block title %}Blog | {{post.title}} {% endblock title %}

{% block body %}

    <article>
        <h1 class="title">#{{post.id}} - {{post.title}}</h1>
        <p class="content">{{post.body}}</p>
    </article>
    

    <p><a href="{% url 'blog:index' %}">All posts</a></p>
{% endblock body %}

templates/layouts/_footer.html
<footer class="footer text-center">
    <p>&copy; Copyright {% now 'Y' %} &middot; Acme &middot; All rights reserved</p>
</footer>

templates/layouts/_nav.html
<nav class="navbar">
   <div class="wrapper">
        <a href="{% url 'home' %}" class="navbar-brand">ACME</a>
        <ul class="navbar-right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'blog:index' %}">Blog</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
        </ul>
   </div>
</nav>

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Acme{% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block stylesheets %}{% endblock %}
</head>
<body>

    {% include 'layouts/_nav.html' %}

   <div class="wrapper">
        {% block content %}{% endblock %}
   </div>

   {% include 'layouts/_footer.html' %}

   {% block javascripts %}{% endblock %}
</body>
</html>

templates/pages/about.html
{% extends 'layouts/base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
    <h1>About</h1>
    <p>
        Occaecat dolor adipisicing aliquip magna do excepteur officia. Sit deserunt amet proident exercitation et proident cupidatat duis ea occaecat voluptate ut. Occaecat adipisicing sit do ex et aliqua. Sunt excepteur esse qui quis adipisicing elit minim in. Id nulla in officia eu velit tempor labore consectetur non irure ea occaecat ut in. Consequat sint ullamco enim occaecat adipisicing fugiat commodo cillum aute occaecat ex laboris. Eiusmod labore cupidatat aliquip magna est qui tempor anim ad in reprehenderit voluptate proident fugiat.

    Ad Lorem incididunt est sunt consectetur nostrud consectetur id elit ea. Occaecat dolor ad amet nisi veniam adipisicing enim amet. Culpa cupidatat commodo esse velit eiusmod culpa cillum nostrud dolore cupidatat ea aute. Dolore pariatur dolor in consectetur consequat commodo nulla eu consectetur anim magna irure anim anim.
    </p>

{% endblock content %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}

{% block title %}Contact{% endblock title %}

{% block content %}

    <h1>Contact</h1>
    <p>
        Sunt sint culpa irure dolor eu elit et irure laborum officia do sint. Eu aliquip dolore qui sit laboris minim non esse aliqua sunt aliquip qui amet cupidatat. Est veniam excepteur sit reprehenderit nisi. Occaecat aute sint sint nisi et est. Quis incididunt nulla dolore pariatur. Pariatur consequat incididunt cupidatat labore exercitation irure.

    Pariatur duis dolor consequat minim non culpa id dolore id ad consectetur et nulla. Aliqua consequat excepteur deserunt reprehenderit nulla aliquip in nostrud reprehenderit tempor ipsum labore pariatur. Quis non velit magna nulla do velit eu commodo exercitation id.
    </p>

{% endblock content %}

templates/pages/home.html
{% extends 'layouts/base.html' %}

{% block title %}Homepage | Acme {% endblock title %}

{% block content %}

<h1>Hello Acme</h1>

<p><a href="{% url 'blog:index' %}">Visiter notre blog</a></p>

{% endblock %}